### ISSUE TITLE
Can't post screenshots to Report Portal

### ISSUE THREAD

**Issue by wsbaser** [reportportal/logger-net-nlog#1]
Approach using RP_MESSAGE prefix, that I saw in example-java-TestNG-logback project does not work.
Log.Info($"RP_MESSAGE#BASE64#{base64String}#I'm logging content via BASE64");

**Comment by nvborisenko** [comment]
You can use another approach via ReportPortal.Client.

Example of code to send a screenshot directly to ReportPortal in your code/test/addin:
```csharp
var image = ScreenshotCapture.TakeScreenshot(true);                   
var imageConverter = new ImageConverter();                   
Bridge.Service.AddLogItem(new AddLogItemRequest
{                        
  Level = LogLevel.Info,
  TestItemId = Bridge.Context.TestId,
  Text = "Screenshot",
  Time = DateTime.UtcNow,
  Attach = new Attach("Screenshot", "image/png", (byte[])imageConverter.ConvertTo(image, typeof(byte[])))
});
```

where *Bridge.Service* is object to interact with RP API, *Bridge.Context.TestId* is your running test.

The behavior might be changed due we need support several tests under running.

**Comment by DzmitryHumianiuk** [comment]
Refer to example
https://github.com/reportportal/example-net-nunit/blob/master/src/Example/Tests/Class1.cs

**Comment by KunalShokeen432** [comment]
@DzmitryHumianiuk Can you please provide an example to attach screenshot for TestNG + Java ?
Thanks

**Comment by DzmitryHumianiuk** [comment]
@KunalShokeen432 https://github.com/reportportal/example-java-TestNG/blob/master/logback/src/main/java/com/epam/rp/tests/logging/LoggingTest.java

**Comment by shilpa25comp** [comment]
I am using mstest:

 screenshot = (this.driver).GetScreenshot();
this.testContext.AddResultFile(fullFilePath);
 screenshot.SaveAsFile(fullFilePath, System.Drawing.Imaging.ImageFormat.Jpeg);
 Logger.LogInfo(relativeFilePath);

I am seeing a log with relative path in RP with attachment but attachment is blank.
Can you please help me understand what am I missing?

**Comment by nvborisenko** [comment]
@shilpa25comp please create a separate issue with details:
- versions of agent
- some useful screenshots
- any `ReportPortal.*.log` files

Thanks for understanding.

**Comment by PriyankaMahanty** [comment]
@DzmitryHumianiuk Can you please provide an example to attach screenshot for failed test cases in cucumber js ?

**Comment by DzmitryHumianiuk** [comment]
@PriyankaMahanty 
https://github.com/reportportal/agent-js-cucumber
https://github.com/reportportal/agent-js-cucumber#attachments
https://github.com/reportportal/examples-js/tree/master/example-cucumber
