### ISSUE TITLE
Will ReportPortal.NLog be supported for versions of ReportPortal.Shared after 1.5.0?

### ISSUE THREAD

**Issue by mbnovick** [reportportal/logger-net-nlog#2]
I can't used ReportPortal.NLog package because it requires that the version of ReportPortal.Shared to be no more than 1.5.0. Will ReportPortal.NLog soon work with higher versions of ReportPortal.Shared? Current version of ReportPortal.Shared is 2.0.4.

If it won't be supported, what's the best alternative? Use log4net and ReportPortal.Log4Net instead? Write some code on my own to add an appender for NLog?

**Comment by nvborisenko** [comment]
@mbnovick definitely this is issue. This restriction is already removed in 1.1.9-beta1. Need some time to release it.
